export const ENDPOINTS = {
    LOGIN: `/users/login`,
    SIGNUP: `/users/create`,
    VERIFY_EMAIL: '/users/verify-email',
    VERIFY_CODE: '/users/verify-otp',
    RESET_PASSWORD: '/users/reset-password/',
    EXPERIENCE_LEVEL: '/experience-level',
    FITNESS_GOAL: '/fitness-goal',
    SOCIAL_PREFERENCES: '/social-preference',
    RUNNING_TIME: '/running-time',
    SOCIAL_LINKS: '/social-link?user_id=',
    CATEGORY: "/category",
    CREATE_SOCIAL_LINK: "/social-link/create",
    CREATE_GOALS: "/fitness-goal/create",
    CREATE_CLUB_GOALS: "/club-goals/create",
    CREATE_ROUTE: "/routes/create",
    CREATE_CLUB: "/clubs/create",
    UPDATE_CLUB: "/clubs/",
    CREATE_CLUB_RULES: "/club-rules/create",
    CREATE_SCHEDULE: "/schedule/create",
    PAYMENT_INTENT: "/payments/create-intent",
    FOLLOW_USER: "/users/follow",
    ADD_REVIEW: "/reviews/create",
    CREATE_POST: "/posts/create",
    UPDATE_CLUB_POST: "/posts/",
    CREATE_HIGHLIGHT: "/highlights/create",
    UPDATE_HIGHLIGHT: "/highlights/"

};